### ISSUE TITLE
Frequent couldn't found tkk from google translation url

### ISSUE THREAD

**Issue by 283180432** [mind1949/googletrans#4]
Frequent couldn't found tkk from google translation url
It's about half the time

**Comment by mind1949** [comment]
It seems that Google has adjusted its anti scraping techniques.
Please test this #5 PR

**Comment by 283180432** [comment]
> It seems that Google has adjusted its anti scraping techniques.
> Please test this #5 PR

It will still appear whether Google has imposed restrictions on IP

**Comment by mind1949** [comment]
> > It seems that Google has adjusted its anti scraping techniques.
> > Please test this #5 PR
> 
> It will still appear whether Google has imposed restrictions on IP

maybe. Try to slow down your translation?

**Comment by 283180432** [comment]
> > > It seems that Google has adjusted its anti scraping techniques.
> > > Please test this #5 PR
> > 
> > 
> > It will still appear whether Google has imposed restrictions on IP
> 
> maybe. Try to slow down your translation?

It is possible to reduce the number of occurrences, but it may be better to add a proxy

**Comment by mind1949** [comment]
> > > > It seems that Google has adjusted its anti scraping techniques.
> > > > Please test this #5 PR
> > > 
> > > 
> > > It will still appear whether Google has imposed restrictions on IP
> > 
> > 
> > maybe. Try to slow down your translation?
> 
> It is possible to reduce the number of occurrences, but it may be better to add a proxy

If you have a good solution, welcome PR 😄

**Comment by mind1949** [comment]
After adding a retry mechanism #5, the problem seems to be resolved for me @283180432
