### ISSUE TITLE
couldn't found tkk from google translation url 

### ISSUE THREAD

**Issue by xiusin** [mind1949/googletrans#6]
can't match tkk

```
TestGoogleTranslate: google_test.go:9:  couldn't found tkk from google translation url
```

**Comment by mind1949** [comment]
it seems that google translate has completely changed his api 😑

**Comment by xiusin** [comment]
Why can't just request their webapi

**Comment by mind1949** [comment]
> Why can't just request their webapi

it's webapi and algorithms have been completely changed, this project needs to be rewritten according to [the new api](https://translate.google.cn/)

**Comment by 283180432** [comment]
Had the same problem

**Comment by mind1949** [comment]
> Had the same problem

This project needs to be rewritten, please wait

**Comment by 283180432** [comment]
> > Had the same problem
> 
> This project needs to be rewritten, please wait

Rewrite can consider adding proxy to avoid IP being blocked by Google

**Comment by amen160** [comment]
Hi @mind1949 any update for this

**Comment by yznts** [comment]
@amen160 Adapting to the new webapi changes may take some time. It's not official API and needs reverse engineering

**Comment by huangyunbo** [comment]
页面不含有tkk了，有什么新的思路吗？

**Comment by amen160** [comment]
Hi @mind1949 any update for this.

**Comment by amen160** [comment]
@xiusin  any update for this? why you close this?
